version: '3.1'

services:

# spring auth app service
 spring-auth:
    image: spring-mongo-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      
      
 mongodb:
      image: mongo
      restart: always
      ports:
         - "27017:27017"